services:
  - type: web
    name: chillimania-portfolio
    env: node
    buildCommand: npm run build
    startCommand: node server.js
    publishDirectory: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
